(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],P=window.PROJECTS,BASE='/portfolio/assets/',mobile=matchMedia('(max-width:760px)');
const state={selected:0,filter:'all',query:'',image:0,z:5,viewer:false,app:'work',command:0};let returnFocus=null,cmdItems=[],exhibitionObserver=null,explorerScroll={list:0,x:0,body:0};const reduced=matchMedia('(prefers-reduced-motion:reduce)');
function enter(el,kind='resolve'){
 if(reduced.matches)return;el.getAnimations().forEach(a=>a.cancel());
 const from={opacity:0,transform:kind==='travel'?'translateX(20px)':kind==='warm'?'translateY(16px) scale(.985)':'translateY(10px)'};
 const to={opacity:1,transform:'translate(0,0) scale(1)'};
 if(kind==='page'){from.clipPath='inset(0 0 9% 0)';to.clipPath='inset(0 0 0 0)'}
 el.animate([from,to],{duration:kind==='warm'?560:420,easing:'cubic-bezier(.22,1,.36,1)'});
}
function remember(){sessionStorage.setItem('vt-selected',P[state.selected].id)}
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const category=p=>p.category.includes('identity')?'identity':p.category.includes('Campaign')?'campaign':'other';
const image=(p,n,loading='lazy')=>`<img src="${BASE+p.images[n]}" alt="${escape(p.name)} — original artwork ${n+1}" loading="${loading}" decoding="async" ${window.ART_SIZES[p.images[n]]?`width="${window.ART_SIZES[p.images[n]][0]}" height="${window.ART_SIZES[p.images[n]][1]}"`:""}>`;
function announce(s){$('#announcement').textContent=s}function focusApp(id){const el=$('#'+id);$$('.window').forEach(w=>w.classList.remove('front'));el.style.zIndex=++state.z;el.classList.add('front');state.app=id;syncDock()}
function syncDock(){const home=mobile.matches&&!state.viewer&&$$('.window').every(w=>w.hidden);document.body.dataset.screen=state.viewer?'exhibition':home?'home':state.app;$('.pocket-home').hidden=!home;$$('[data-app]').forEach(b=>b.setAttribute('aria-pressed',String(state.viewer?b.dataset.app==='work':!$('#'+b.dataset.app).hidden&&state.app===b.dataset.app)))}
function openApp(id,route=true){if(state.viewer)workspace(false);if(mobile.matches)$$('.window').forEach(w=>w.hidden=w.id!==id);else {$$('.utility-window').forEach(w=>w.hidden=w.id!==id);$('#'+id).hidden=false;}focusApp(id);if(id==='work')revealSelected();$('#'+id).focus({preventScroll:true});if(id!=='motion')$('#reel').pause();if(route)history.pushState({selected:P[state.selected].id},'', '/#'+({work:'workspace',profile:'about',connect:'contact',motion:'motion'}[id]));document.title='VT.OS / '+({work:'Projects',profile:'About',connect:'Contact',motion:'Motion'}[id]);enter($('#'+id));announce(({work:'Projects',profile:'About',connect:'Contact',motion:'Motion'}[id])+' opened')}
function minimize(id){$('#'+id).hidden=true;if(mobile.matches){history.pushState({selected:P[state.selected].id},'','/#home');document.title='VT Pocket OS / Home';}if(id==='motion')$('#reel').pause();syncDock();const b=$('.dock [data-app="'+id+'"]');b.focus();announce(id+' minimized. Reopen from the dock.')}
function renderList(){const focused=document.activeElement?.dataset.select,oldScroll=$('#project-list').scrollTop,oldX=$('#project-list').scrollLeft;let visible=P.map((p,i)=>({p,i})).filter(({p})=>(state.filter==='all'||category(p)===state.filter)&&(p.name+' '+p.category).toLowerCase().includes(state.query));$('#project-list').innerHTML=visible.map(({p,i})=>`<button class="project-row" data-select="${i}" ${i===state.selected?'aria-current="true"':''}><span>${String(i+1).padStart(2,'0')}</span><span><strong>${escape(p.name)}</strong><small>${escape(p.category)}</small></span></button>`).join('');$('#empty').hidden=!!visible.length;$('#item-count').textContent=visible.length+' PROJECTS';$('#project-list').scrollTop=oldScroll;$('#project-list').scrollLeft=oldX;if(focused!==undefined)$('[data-select="'+focused+'"]')?.focus({preventScroll:true});}
function revealSelected(){const row=$('[data-select="'+state.selected+'"]');if(!row||!mobile.matches||$('#work').hidden)return;const list=$('#project-list'),r=row.getBoundingClientRect(),v=list.getBoundingClientRect();if(r.left<v.left+12)list.scrollLeft-=v.left+12-r.left;else if(r.right>v.right-12)list.scrollLeft+=r.right-v.right+12;}
function select(i){state.selected=i;remember();if(!state.viewer&&location.pathname==='/'&&location.hash==='#workspace')history.replaceState({selected:P[i].id},'',location.href);state.image=0;const p=P[i];$('#preview-title').textContent=p.name;$('#preview-category').textContent=p.category;$('#preview-description').textContent=p.description;$('#preview-image').src=BASE+p.images[0];$('#preview-image').alt=p.name+' — original artwork';$('#preview-art').style.setProperty('--tone',category(p)==='identity'?'#e8e2d6':p.tone);$('#selected-index').textContent=String(i+1).padStart(2,'0')+' / '+String(P.length).padStart(2,'0');$('#asset-count').textContent=p.images.length+' ORIGINAL '+(p.images.length===1?'ARTWORK':'ARTWORKS');$('#preview-art').setAttribute('aria-label','View Project: '+p.name);renderList();revealSelected()}
function artworkFigure(p,n,cls=''){return `<figure class="exhibit-piece ${cls}" style="--piece-order:${n%3}"><button data-art="${n}" aria-label="Fullscreen: ${escape(p.name)} artwork ${n+1}">${image(p,n,n===0?'eager':'lazy')}</button><figcaption><span>Artwork ${String(n+1).padStart(2,'0')}</span><span>Click / tap to inspect ⤢</span></figcaption></figure>`}
function openProject(i,route=true){
 if(!state.viewer)explorerScroll={list:$('#project-list').scrollTop,x:$('#project-list').scrollLeft,body:$('.explorer').scrollTop};
 select(i);state.viewer=true;$('#reel').pause();$('.desktop').hidden=true;$('#viewer').hidden=false;
 syncDock();const p=P[i],d=window.EXHIBITIONS[p.id],next=P[(i+1)%P.length];
 const viewer=$('#viewer');viewer.dataset.layout=d.layout;viewer.dataset.motion=d.motion;
 viewer.style.setProperty('--exhibit-surface',d.surface);viewer.style.setProperty('--exhibit-ink',d.ink);
 $('#viewer-location').textContent='VT.OS / '+p.category.toUpperCase();$('#viewer-next').setAttribute('aria-label','Next Project: '+next.name);let visibleChapter=0;
 const chapters=d.chapters.map(([from,title,note],ci)=>{
  const to=d.chapters[ci+1]?.[0]??p.images.length;if(Math.max(1,from)>=to)return '';
  return `<section class="exhibition-chapter" aria-labelledby="chapter-${ci}"><div class="chapter-heading"><span class="chapter-label">${String(++visibleChapter).padStart(2,'0')} / ${escape(title)}</span><h2 id="chapter-${ci}">${escape(note)}</h2></div><div class="exhibition-gallery">${p.images.slice(Math.max(1,from),to).map((_,j)=>artworkFigure(p,Math.max(1,from)+j,(j%3===2?'exhibit-wide':''))).join('')}</div></section>`;
 }).join('');
 $('#case-content').innerHTML=`<header class="exhibition-opening"><div class="exhibition-intro"><span class="case-number">EXHIBITION / ${String(i+1).padStart(2,'0')}</span><h1 class="case-title" tabindex="-1">${escape(p.name)}</h1><p class="exhibition-statement">${escape(d.heading)}</p><div class="exhibition-context"><p class="exhibition-description">${escape(p.description)}</p><div class="exhibition-meta"><span>${escape(p.category)}</span><span>Vishal Tyagi</span></div><span class="exhibition-instruction">${p.images.length>1?'Scroll to explore · Click artwork for fullscreen':'Click artwork for fullscreen'}</span></div></div>${artworkFigure(p,0,'opening-art')}</header>${chapters}<section class="exhibition-next"><div><span class="eyebrow">NEXT IN THE COLLECTION</span><h2>${escape(next.name)}</h2></div><div class="project-turn"><button id="previous-project">← Previous Project</button></div></section>`;
 if(route)history.pushState({project:p.id},'', '/portfolio/#'+p.id);
 viewer.scrollTop=0;$('.case-title').focus({preventScroll:true});document.title=p.name+' — VT.OS / Exhibition';
 enter($('.exhibition-opening'),d.motion);exhibitionObserver?.disconnect();
 if(!reduced.matches){exhibitionObserver=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){enter(e.target,d.motion);exhibitionObserver.unobserve(e.target)}})},{root:viewer,threshold:.12});$$('.exhibition-chapter').forEach(el=>exhibitionObserver.observe(el))}
 announce(p.name+' exhibition opened');
}
function workspace(route=true){exhibitionObserver?.disconnect();state.viewer=false;$('#viewer').hidden=true;$('.desktop').hidden=false;if(route)history.pushState({selected:P[state.selected].id},'','/#workspace');$('#work').hidden=false;if(mobile.matches)$$('.window').forEach(w=>w.hidden=w.id!=='work');focusApp('work');window.scrollTo(0,0);document.title='VT.OS — Vishal Tyagi / Creative Workspace';$('#project-list').scrollTop=explorerScroll.list;$('#project-list').scrollLeft=explorerScroll.x;revealSelected();$('.explorer').scrollTop=explorerScroll.body;enter($('#work'));$('#view-project').focus({preventScroll:true});announce('Workspace restored. '+P[state.selected].name+' selected.')}
function renderPresentation(){const p=P[state.selected];$('#presentation').style.setProperty('--presentation-surface',window.EXHIBITIONS[p.id].surface);$('#presentation').style.setProperty('--tone',category(p)==='identity'?'#e8e2d6':p.tone);$('#presentation-title').textContent=p.name;$('#presentation-image').src=BASE+p.images[state.image];$('#presentation-image').alt=p.name+' — original artwork '+(state.image+1);$('#image-index').textContent=(state.image+1)+' / '+p.images.length;$('#image-prev').disabled=p.images.length<2;$('#image-next').disabled=p.images.length<2;$('#image-prev').hidden=$('#image-next').hidden=p.images.length<2;}
function present(n=0){state.image=n;returnFocus=document.activeElement;renderPresentation();$('#presentation').showModal();$('#presentation-close').focus();enter($('.presentation-image'));}
function stepImage(delta){const p=P[state.selected];state.image=(state.image+delta+p.images.length)%p.images.length;renderPresentation();enter($('.presentation-image'));}
function commandResults(){const q=$('#command-search').value.toLowerCase();cmdItems=[{name:'Projects Explorer',app:'work'},{name:'About Vishal',app:'profile'},{name:'Motion.player',app:'motion'},{name:'Contact / Hire Me',app:'connect'},...P.map((p,i)=>({name:p.name,i}))].filter(c=>c.name.toLowerCase().includes(q));state.command=Math.min(state.command,Math.max(0,cmdItems.length-1));$('#command-results').innerHTML=cmdItems.length?cmdItems.map((c,i)=>`<button class="command-item ${i===state.command?'selected':''}" data-command="${i}"><span>${escape(c.name)}</span><small>${c.app?'Open app':'View Project'} ↗</small></button>`).join(''):'<p style="padding:20px">No matches. Try another project or app.</p>'}
function commands(){returnFocus=document.activeElement;state.command=0;$('#command-search').value='';commandResults();$('#commands').showModal();$('#command-search').focus()}
function runCommand(i){const c=cmdItems[i];if(!c)return;$('#commands').close();c.app?openApp(c.app):openProject(c.i)}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.select!==undefined){select(+b.dataset.select);announce(P[state.selected].name+' selected')}else if(b.dataset.app)openApp(b.dataset.app);else if(b.dataset.min)minimize(b.dataset.min);else if(b.dataset.max){const w=$('#'+b.dataset.max);w.classList.toggle('maximized');b.setAttribute('aria-label',(w.classList.contains('maximized')?'Restore ':'Maximize ')+b.dataset.max);focusApp(w.id)}else if(b.dataset.action==='workspace')workspace();else if(b.dataset.action==='commands')commands();else if(b.dataset.filter){state.filter=b.dataset.filter;$$('[data-filter]').forEach(f=>f.setAttribute('aria-pressed',String(f===b)));renderList()}else if(b.dataset.art!==undefined)present(+b.dataset.art);else if(b.dataset.command!==undefined)runCommand(+b.dataset.command);else if(b.dataset.close)$('#'+b.dataset.close).close();else if(b.id==='view-project'||b.id==='preview-art')openProject(state.selected);else if(b.id==='viewer-fullscreen'||b.id==='preview-fullscreen')present();else if(b.id==='previous-project')openProject((state.selected-1+P.length)%P.length);else if(b.id==='viewer-next')openProject((state.selected+1)%P.length);else if(b.id==='image-prev')stepImage(-1);else if(b.id==='image-next')stepImage(1);else if(b.id==='presentation-close')$('#presentation').close();else if(b.id==='boot-enter'){sessionStorage.setItem('vt-boot','1');$('#boot').close();openApp('work')}else if(b.dataset.reel){$('#reel').pause();$('#reel').src=BASE+'motion-'+b.dataset.reel+'.mp4';$('#reel').poster=BASE+'motion-'+b.dataset.reel+(b.dataset.reel==='selected'?'.png':'.jpg');$('#reel').setAttribute('aria-label','Original '+b.dataset.reel+(b.dataset.reel==='selected'?' motion clip':' motion work'));$$('[data-reel]').forEach(r=>r.setAttribute('aria-pressed',String(r===b)));}});
$('#project-search').addEventListener('input',e=>{state.query=e.target.value.trim().toLowerCase();renderList()});$('#command-search').addEventListener('input',()=>{state.command=0;commandResults()});
$('#commands').addEventListener('keydown',e=>{if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();state.command=(state.command+(e.key==='ArrowDown'?1:-1)+cmdItems.length)%Math.max(cmdItems.length,1);commandResults();$('.command-item.selected')?.scrollIntoView({block:'nearest'})}else if(e.key==='Enter'){e.preventDefault();runCommand(state.command)}});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();if(!$('#boot').open&&!$('#presentation').open)$('#commands').open?$('#commands').close():commands()}if($('#presentation').open){if(e.key==='ArrowRight'){e.preventDefault();stepImage(1)}if(e.key==='ArrowLeft'){e.preventDefault();stepImage(-1)}}else if(state.viewer&&!$('#commands').open&&!e.target.closest('input,textarea,select')&&(e.key==='ArrowRight'||e.key==='ArrowLeft')){e.preventDefault();openProject((state.selected+(e.key==='ArrowRight'?1:-1)+P.length)%P.length)}else if(e.key==='Escape'&&!$('#commands').open&&!$('#boot').open){if(state.viewer){e.preventDefault();workspace()}else{const w=$('#'+state.app);if(w.classList.contains('maximized'))w.classList.remove('maximized');else if(!w.hidden)minimize(state.app)}}});
[$('#commands'),$('#presentation')].forEach(d=>{d.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const stops=[...d.querySelectorAll('button:not(:disabled),input,a[href]')].filter(el=>el.getClientRects().length);const first=stops[0],last=stops[stops.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}});d.addEventListener('close',()=>{if(returnFocus?.isConnected)returnFocus.focus({preventScroll:true})});d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}})});
$$('.window').forEach(w=>{w.addEventListener('pointerdown',()=>focusApp(w.id));let drag=null;const bar=w.querySelector('.titlebar');bar.addEventListener('pointerdown',e=>{if(mobile.matches||w.classList.contains('maximized')||e.target.closest('button')||e.button!==0)return;const r=w.getBoundingClientRect(),stage=$('.desktop').getBoundingClientRect();drag={x:e.clientX,y:e.clientY,left:r.left-stage.left,top:r.top-stage.top};bar.setPointerCapture(e.pointerId);bar.style.cursor='grabbing'});bar.addEventListener('pointermove',e=>{if(!drag)return;const stage=$('.desktop');w.style.left=Math.max(0,Math.min(stage.clientWidth-w.offsetWidth,drag.left+e.clientX-drag.x))+'px';w.style.top=Math.max(0,Math.min(stage.clientHeight-100-w.offsetHeight,drag.top+e.clientY-drag.y))+'px';w.style.right='auto'});const stop=()=>{drag=null;bar.style.cursor=''};bar.addEventListener('pointerup',stop);bar.addEventListener('pointercancel',stop);bar.addEventListener('dblclick',e=>{if(!mobile.matches&&!e.target.closest('button')){w.classList.toggle('maximized');w.querySelector('[data-max]').setAttribute('aria-label',(w.classList.contains('maximized')?'Restore ':'Maximize ')+w.id)}})});
function route(){const id=location.hash.slice(1),aliases={identity:'resultbull',campaigns:'ascott',print:'ginger',additional:'archive',radisson:'rcz'},i=P.findIndex(p=>p.id===(aliases[id]||id));if(i>=0){$('#boot').close();openProject(i,false)}else if(id==='home'&&!mobile.matches){workspace(false)}else if(id==='home'){state.viewer=false;$('#viewer').hidden=true;$('.desktop').hidden=false;$$('.window').forEach(w=>w.hidden=true);$('#reel').pause();syncDock()}else if(id==='workspace'){const restored=P.findIndex(p=>p.id===history.state?.selected);if(restored>=0)select(restored);workspace(false)}else if(id==='motion'||id==='about'||id==='contact'){workspace(false);openApp(id==='about'?'profile':id==='contact'?'connect':'motion',false)}else{if(history.state?.selected){const si=P.findIndex(p=>p.id===history.state.selected);if(si>=0)select(si)}if(state.viewer)workspace(false)}}window.addEventListener('popstate',route);window.addEventListener('hashchange',route);
reduced.addEventListener('change',()=>{if(reduced.matches){exhibitionObserver?.disconnect();document.getAnimations().forEach(a=>a.cancel());$('#reel').pause()}});
mobile.addEventListener('change',()=>{if(mobile.matches)$$('.window').forEach(w=>w.hidden=w.id!==state.app);else{ $('#work').hidden=false;$('#profile').hidden=false;$$('.window').forEach(w=>{w.style.left='';w.style.top='';w.style.right='';w.classList.remove('maximized')})}syncDock();revealSelected()});
document.addEventListener('error',e=>{if(e.target.tagName==='IMG'){e.target.parentElement.classList.add('image-error');announce('An artwork could not load. Reopen the project to retry.')}},true);
const saved=P.findIndex(p=>p.id===sessionStorage.getItem('vt-selected'));select(saved>=0?saved:0);if(mobile.matches)$('#profile').hidden=true;syncDock();route();if(!location.hash&&!sessionStorage.getItem('vt-boot'))$('#boot').showModal();
})();

