import assert from "node:assert/strict";
import {chromium} from "playwright";
import {pathToFileURL} from "node:url";
import {resolve} from "node:path";
import {stat} from "node:fs/promises";
const base=resolve("dist/vt-shift");
const browser=await chromium.launch({headless:true,args:["--disable-dev-shm-usage"]});
const page=await browser.newPage({viewport:{width:1280,height:800}});
const errors=[];
page.on("pageerror",e=>errors.push(e.message));
const fileUrl=pathToFileURL(resolve(base,"index.html")).href;
await page.goto(fileUrl,{waitUntil:"domcontentloaded"});
await page.waitForTimeout(550);
assert.equal(await page.locator(".visual-scene").count(),5);
await page.locator(".scene-asr .art-main").evaluate(img=>img.decode());
assert((await page.locator(".scene-asr .art-main").evaluate(img=>img.naturalWidth))>100,"Original offline image didn't load");
await page.locator('[data-index="3"]').click();
await page.waitForFunction(()=>document.querySelector("#art-title").textContent==="Pride Hotels");
await page.locator("#open-study").click();
await page.waitForFunction(()=>document.querySelector("#study").open);
assert.equal(await page.locator("#study-gallery img").count(),2);
for(const img of await page.locator("#study-gallery img").all()){await img.evaluate(e=>e.decode());assert((await img.evaluate(e=>e.naturalWidth))>50)}
await page.keyboard.press("Escape");
assert.equal(await page.locator("#study").evaluate(e=>e.open),false);
assert((await stat(resolve(base,"assets/motion-selected.mp4"))).size>50000);
assert((await stat(resolve(base,"assets/Vishal-Tyagi-Resume.pdf"))).size>3000);
assert.deepEqual(errors,[],"Browser JS should run from actual local file://");
// The self-contained HTML must actually run from file://, not merely contain base64 assets.
const allinone=await browser.newPage({viewport:{width:1280,height:800}});
const standaloneErrors=[];
allinone.on("pageerror",e=>standaloneErrors.push(e.message));
await allinone.goto(pathToFileURL(resolve("dist/VT_SHIFT_STANDALONE.html")).href,{waitUntil:"domcontentloaded"});
await allinone.waitForTimeout(550);
assert.equal(await allinone.locator(".visual-scene").count(),5);
await allinone.locator(".scene-asr .art-main").evaluate(img=>img.decode());
assert((await allinone.locator(".scene-asr .art-main").evaluate(img=>img.naturalWidth))>200);
await allinone.locator('[data-index="2"]').click();
await allinone.waitForFunction(()=>document.querySelector("#art-title").textContent==="GTM Leads");
await allinone.locator("#open-study").click();
await allinone.waitForFunction(()=>document.querySelector("#study").open);
const singleImage=await allinone.locator("#study-image").evaluate(async img=>{let error="";try{await img.decode()}catch(e){error=e.message}return{naturalWidth:img.naturalWidth,complete:img.complete,src:img.src.slice(0,85),sourceLength:img.src.length,error}});
console.log("VT SHIFT STANDALONE IMAGE DEBUG: "+JSON.stringify(singleImage));
assert(singleImage.complete&&singleImage.naturalWidth>=100&&singleImage.sourceLength>5000&&singleImage.src.startsWith("data:image/svg+xml;base64,"),JSON.stringify(singleImage));
assert((await allinone.locator("#motion source").getAttribute("src")).startsWith("data:video/mp4;base64,"));
assert((await allinone.locator(".about-metadata a").getAttribute("href")).startsWith("data:application/pdf;base64,"));
assert.deepEqual(standaloneErrors,[],"Standalone HTML runtime errors");
await allinone.close();
console.log("VT SHIFT STANDALONE HTML TEST: PASS — original brand art, fullscreen viewer, video and resume embedded; file:// works.");
await browser.close();
console.log("VT SHIFT OFFLINE DEMO TEST: PASS — five original compositions, intact image gallery, original showreel and resume, direct local file:// launch.");
