import assert from "node:assert/strict";
import {chromium} from "playwright";
import {pathToFileURL} from "node:url";
import {resolve} from "node:path";
import {stat} from "node:fs/promises";
const base=resolve("dist/vt-shift");
const browser=await chromium.launch({headless:true,args:["--disable-dev-shm-usage"]});
const page=await browser.newPage({viewport:{width:1280,height:800}});
const errors=[];
page.on("pageerror",e=>errors.push(e.message));
const fileUrl=pathToFileURL(resolve(base,"index.html")).href;
await page.goto(fileUrl,{waitUntil:"domcontentloaded"});
await page.waitForTimeout(550);
assert.equal(await page.locator(".visual-scene").count(),5);
await page.locator(".scene-asr .art-main").evaluate(img=>img.decode());
assert((await page.locator(".scene-asr .art-main").evaluate(img=>img.naturalWidth))>100,"Original offline image didn't load");
await page.locator('[data-index="3"]').click();
await page.waitForFunction(()=>document.querySelector("#art-title").textContent==="Pride Hotels");
await page.locator("#open-study").click();
await page.waitForFunction(()=>document.querySelector("#study").open);
assert.equal(await page.locator("#study-gallery img").count(),2);
for(const img of await page.locator("#study-gallery img").all()){await img.evaluate(e=>e.decode());assert((await img.evaluate(e=>e.naturalWidth))>50)}
await page.keyboard.press("Escape");
assert.equal(await page.locator("#study").evaluate(e=>e.open),false);
assert((await stat(resolve(base,"assets/motion-selected.mp4"))).size>50000);
assert((await stat(resolve(base,"assets/Vishal-Tyagi-Resume.pdf"))).size>3000);
assert.deepEqual(errors,[],"Browser JS should run from actual local file://");
await browser.close();
console.log("VT SHIFT OFFLINE DEMO TEST: PASS — five original compositions, intact image gallery, original showreel and resume, direct local file:// launch.");
